### ISSUE TITLE
Create and style Sign in/ Create an Account page

### ISSUE THREAD

**Issue by Shilohjones194** [lilyhi/surviving-cbc#8]
Discuss this in tomorrows class on what we can add for future developments:

![image](https://user-images.githubusercontent.com/76697212/129139714-258652ae-5048-4d69-bbaf-4c51be0c8775.png)

**Comment by pablodlc** [comment]
Creating page w/ two side-by-side cards: Sign Up will look similar to Luke's image above. Log In will be a simplified version with just username and password.

**Comment by Shilohjones194** [comment]
![image](https://user-images.githubusercontent.com/76697212/129513478-9277c92d-732e-42a5-b96e-2f1f0f4b9935.png)
Pablo knocked this one out of the park in Record time!

**Comment by pablodlc** [comment]
Created a `Suli.js` file with `Suli()` function. They serve  as the Sign Up or Log In page.  I'm including an image of the page's current look.  I'm creating a new Issue to style this page.
I included the following routes that will link to such page: 

- `/signup`
- `/login`
- `/register`
- `/iwillsurvive`

![image](https://user-images.githubusercontent.com/73490637/129520912-775dbf3c-b087-4a93-8739-dbeddb194d01.png)
